### PR TITLE
Slope limiter and mod

### PR DESCRIPTION
**Pull request by alsgregory**
Alterations:

- Changed slope limiter and modification by limiting each component of state vector and setting spurious momentums to 0 when velocity norm passes threshold.
- Changed flooding example to fit parameters in Ern et al.
- Now do slope limiting on all RK subiterates.

### CODE REVIEW

**Comment by wence-** [comment]
Can we discuss how to incorporate the flooddrake slope limiter stuff into firedrake itself at the meeting this afternoon?

**Comment by alsgregory** [comment]
Yes for sure. This update was a simply a necessary change to the current functionality as it produced major shocks in the altered demo case.

**Comment by wence-** [comment]
Aha, I see.

**Comment by wence-** [comment]
I thought this looked fine.

**Pull request merged**
